name: Update CHANGELOG.md

on:
  pull_request_review:
    branches:
      - master
    types:
      - submitted
  # For manually triggering this workflow
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
env:
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  GH_TOKEN: ${{ github.token }} # This is needed for the GitHub CLI

jobs:
  update_changelog:
    if: github.repository_owner == 'vladsavelyev' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Check if CHANGELOG.md was modified by other commits (including previous runs of this workflow)
        run: |
          pr_number=${{ github.event.pull_request.number }}
          files=$(gh pr diff $pr_number --name-only)
          if [[ $files == *"CHANGELOG.md"* ]]; then
            echo "CHANGELOG.md was modified in this PR"
            echo "changelog_modified=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not modified in this PR"
            echo "changelog_modified=false" >> $GITHUB_ENV
          fi

      - name: Update CHANGELOG.md from the PR title
        if: env.changelog_modified == 'false'
        run: python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        run: |
          git diff --exit-code CHANGELOG.md || echo "changed=YES" >> $GITHUB_ENV
          echo "file changed: ${{ env.changed }}"

      - name: Commit and push if changed
        if: env.changed == 'YES'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "multiqc-bot@seqera.io"
          git config --global user.name "MultiQC Bot"
          gh pr checkout ${{ github.event.pull_request.number }}        
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
